# Generated by Django 2.2.7 on 2019-11-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnswerModel', to='overflow.ReplyModel'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replymodel',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReplyModel', to='overflow.QuestionModel'),
        ),
    ]
