# Generated by Django 2.2.7 on 2019-11-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0004_questionmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='tag',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
