# Generated by Django 2.2.7 on 2019-11-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0007_auto_20191125_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replymodel',
            name='question',
        ),
        migrations.AddField(
            model_name='replymodel',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReplyModel', to='overflow.AnswerModel'),
        ),
    ]
