# Generated by Django 2.2.7 on 2019-11-25 13:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0008_auto_20191125_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answer',
            field=ckeditor.fields.RichTextField(max_length=120),
        ),
    ]
