# Generated by Django 2.2.7 on 2019-11-25 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0009_auto_20191125_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answer_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
