# Generated by Django 2.2.7 on 2019-12-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0011_auto_20191202_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='overflow.QuestionModel'),
        ),
        migrations.AlterField(
            model_name='replymodel',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='overflow.AnswerModel'),
        ),
    ]
