# Generated by Django 2.2.7 on 2019-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0012_auto_20191202_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
