# Generated by Django 2.2.7 on 2019-12-23 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overflow', '0013_auto_20191205_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='am_question', to='overflow.QuestionModel'),
        ),
        migrations.CreateModel(
            name='QuestionVoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qvm_question', to='overflow.QuestionModel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qvm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
