# Generated by Django 2.2.7 on 2019-12-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0015_auto_20191225_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='votes',
        ),
    ]
