# Generated by Django 2.2.7 on 2019-12-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0017_auto_20191225_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answervotemodel',
            old_name='question',
            new_name='answer',
        ),
    ]
